language: python

services:
  - docker

before_install:
  - docker build --no-cache -t bjoern36-37 .

script:
  - docker run -t -w /bjoern -v $(pwd):/bjoern bjoern36-37 make all-36
  - docker run -t -w /bjoern -v $(pwd):/bjoern bjoern36-37 make all-37